name: Test Deployment

on:
  workflow_dispatch:

jobs:
  publish_central: # Publish the code to central
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11, 17]
        java-package: [jdk]
        distribution: [temurin]
        include: 
          # When building Java 8 we need JavaFX on JDK basis
          - java: 8
            java-package: jdk+fx
            distribution: zulu

    steps:
    - uses: actions/checkout@v2
    
      # Fixes OSSRH-66257
      # See https://issues.sonatype.org/browse/OSSRH-66257?focusedCommentId=1036973&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1036973
    - if: ${{ matrix.java == 17 }}
      run: |
        echo 'MAVEN_OPTS=--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED' >> $GITHUB_ENV
    
    - name: Set up JDK and configure for ossrh
      uses: actions/setup-java@v2
      with: # running setup-java again overwrites the settings.xml
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
        java-package: ${{ matrix.java-package }}
        server-id: ossrh
        server-username: MAVEN_CENTRAL_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

    - name: Publish to Apache Maven Central
      run: mvn -B deploy -Possrh,java${{ matrix.java }}
      env:
        MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
